import { ConfigInterface } from './contract';

export const config: ConfigInterface = {
  gameWidth: 950,
  gameHeight: 600,
  reelPosition: { x: 10, y: 20},
  playButtonPosition: { x: 100, y: 426 },
  selectEasyModePosition: { x: 640, y: 470 },
  FPSDisplayPosition: { x: 500, y: 20 },
  totalReels: 5,
  reelSpinningCycles: 2,
  reelSpinningSpeedFactor: [100, 40, 35, 30, 25],
  reelShuffleSpinningSpeedFactor: false,
  totalReelCells: 5,
  reelVisibleCells: 5,
  reelCellHeight: 143.5,
  reelCellWidth: 144,
  reelVerticalPadding: 0,
  reelHorizontalMargin: 0 ,
  backgroundHeight: 800,
  backgroundWidth: 600,
  backgroundHorizontalMargin: 0,
  backgroundVerticalPadding: 0,
  backgroundPosition: {x: 10, y: 40},
};
